CREATE DATABASE wordpress;
CREATE USER 'sstyr'@'%' IDENTIFIED BY '123123';
GRANT ALL PRIVILEGES ON wordpress.* TO 'sstyr'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123123';
